import Button from '@/components/Button/Button';
import Htag from '@/components/Htag/Htag';
import Head from 'next/head';
import Typography from '@/components/Typography/Typography';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <main style={{padding: '50px'}}>
        <Htag tag='h1'>Текст</Htag>
        <Button variant='primary'>Кнопка</Button>
        <Button variant='outlined'>Кнопка</Button>
        <Button variant='outlined' arrow='right'>Кнопка</Button>
        <Button variant='primary' arrow='down'>Кнопка</Button>
        <Typography size='l'>Параграф</Typography>
      </main>
    </>
  );
}
