import Button from '@/components/Button/Button';
import Htag from '@/components/Htag/Htag';
import Head from 'next/head';
import Typography from '@/components/Typography/Typography';
import Tag from '@/components/Tag/Tag';
import Rating from '@/components/Rating/Rating';
import { useState } from 'react';
import { GetStaticProps } from 'next';
import axios from 'axios';
import { MenuItem } from '@/interfaces/menu.interface';
import { withLayout } from '@/layout/Layout';
import { API } from '@/helpers/api';

function Home({ menu }: HomeProps) {
  const [rating, setRating] = useState<number>(4);
  return (
    <>
      <Head>
        <title>Top App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <>
      test
      </>
    </>
  );
}

export default withLayout(Home);

export interface HomeProps extends Record<string, unknown> {
  menu: MenuItem[];
  firstCategory: number;
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const firstCategory = 0;
  const { data: menu } = await axios.post<MenuItem[]>(API.topPage.find,
    { firstCategory }
  );

  return {
    props: {
      menu: menu,
      firstCategory
    }
  };
};
